server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

okta:
  oauth2:
    issuer: https://dev-88020100.okta.com/oauth2/default
    audience: api://default