server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mc_user
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-88020100.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            clientId: 0oam18b26eaeiDdc55d7
            clientSecret: NEhi5MYJBivHvqX-wAl_YIZGeoxamEdnRNxFzTWSIskcEFSsNIHGCXzg8Gm2c6YW
        provider:
          okta:
            issuerUri: https://dev-88020100.okta.com/oauth2/default


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka

#Resilience4j Config
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: ALWAYS
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50 # %
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelRetry:
        maxAttempts: 3
        waitDuration: 3s

  ratelimiter:
    instances:
      ratingHotelRateLimiter:
        limitRefreshPeriod: 10s
        limitForPeriod: 2
        timeoutDuration: 0s

okta:
  oauth2:
    issuer: https://dev-88020100.okta.com/oauth2/default
    audience: api://default