server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: ms_service_discovery

spring:
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/user/**


